name: MysticWeaving
version: '1.0-SNAPSHOT'
main: me.tomqnto.mysticWeaving.MysticWeaving
api-version: '1.21'
authors: [ Tomqnto ]

commands:
  add_mystic_dust:
    usage: /<command> <player> <amount>
  mysticgui:
    usage: /<command>
  levelup:
    usage: /<command>
  upgrade_energy_level:
    usage: /<command>
  reset:
    usage: /<command>
  upgrade_energy_regen_amount:
    usage: /<command>
  get_mystic_dust:
    usage: /<command>